### ISSUE TITLE
 ValueError: Caught ValueError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by qunwen** [Binyr/ASDA#5]
when I run train_stn.py in coco datasets, the bug occured , how to solve it?

Traceback (most recent call last):
  File "tools/train_stn.py", line 300, in <module>
    main()
  File "tools/train_stn.py", line 233, in main
    final_output_dir, tb_log_dir, writer_dict, cfg.STN.STN_FIRST)
  File "/root/Desktop/ASDA-master/tools/../lib/core/function.py", line 33, in train
    for i, (input, target, target_weight, meta) in enumerate(train_loader):
  File "/root/anaconda3/envs/ASDA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/ASDA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/ASDA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/ASDA/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.

**Comment by qunwen** [comment]
> when I run train_stn.py in coco datasets, the bug occured , how to solve it?
> 
> Traceback (most recent call last): File "tools/train_stn.py", line 300, in main() File "tools/train_stn.py", line 233, in main final_output_dir, tb_log_dir, writer_dict, cfg.STN.STN_FIRST) File "/root/Desktop/ASDA-master/tools/../lib/core/function.py", line 33, in train for i, (input, target, target_weight, meta) in enumerate(train_loader): File "/root/anaconda3/envs/ASDA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in **next** data = self._next_data() File "/root/anaconda3/envs/ASDA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data return self._process_data(data) File "/root/anaconda3/envs/ASDA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data data.reraise() File "/root/anaconda3/envs/ASDA/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise raise exception ValueError: Caught ValueError in DataLoader worker process 0.
